services:
  postgres:
    image: postgres:14.15-alpine3.21
    container_name: sanda_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: sanda_redis
    restart: always
    ports:
      - "6378:6379"  # Host port 6379 -> Container port 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - redisdata:/data
  app:
    build: .
    container_name: sanda
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file:
      - .env.pg.docker
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  pgdata:
  redisdata:

networks:
  app-network:
    driver: bridge
