---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/registration":
    post:
      summary: Registers a new user
      tags:
      - Registration
      security:
      - x_api_gateway_key: []
      parameters: []
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: Successfully data created
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: John Doe
                      email:
                        type: string
                        example: john.doe@example.com
                      role:
                        type: string
                        example: user
                      status:
                        type: string
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      deleted_at:
                        type: string
                        format: date-time
                        nullable: true
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      example: John Doe
                    email:
                      type: string
                      example: john@example.com
                    password:
                      type: string
                      example: password123
                    status:
                      type: string
                      example: active
                    role:
                      type: string
                      example: user
                  required:
                  - name
                  - email
                  - password
              required:
              - user
  "/api/v1/users":
    get:
      summary: Retrieves paginated users list
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      parameters:
      - name: role
        in: query
        description: Role to filter by
        required: false
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of items per page
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: Users fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully data fetched
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Alice
                        email:
                          type: string
                          example: alice@example.com
                        role:
                          type: string
                          example: user
                        status:
                          type: string
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                        deleted_at:
                          type: string
                          format: date-time
                          nullable: true
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      total_pages:
                        type: integer
                        example: 1
                      total_count:
                        type: integer
                        example: 3
        '401':
          description: Unauthorized
  "/api/v1/users/me":
    get:
      summary: Retrieves current logged in user details
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      responses:
        '200':
          description: User details fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully data fetched
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Alice
                      email:
                        type: string
                        example: alice@example.com
                      role:
                        type: string
                        example: user
                      status:
                        type: string
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      deleted_at:
                        type: string
                        format: date-time
                        nullable: true
        '401':
          description: Unauthorized
    patch:
      summary: Updates current logged in user details
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      parameters: []
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully data updated
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Jane Patched
                      email:
                        type: string
                        example: jane@example.com
                      role:
                        type: string
                        example: user
                      status:
                        type: string
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      deleted_at:
                        type: string
                        format: date-time
                        nullable: true
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Jane Doe
                    email:
                      type: string
                      example: jane@example.com
                    status:
                      type: string
                      example: active
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: User ID
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a user
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      responses:
        '200':
          description: User fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully data fetched
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Alice
                      email:
                        type: string
                        example: alice@example.com
                      role:
                        type: string
                        example: user
                      status:
                        type: string
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      deleted_at:
                        type: string
                        format: date-time
                        nullable: true
        '404':
          description: User not found
    put:
      summary: Updates a user
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      parameters: []
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully data updated
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Jane Updated
                      email:
                        type: string
                        example: jane@example.com
                      role:
                        type: string
                        example: user
                      status:
                        type: string
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      deleted_at:
                        type: string
                        format: date-time
                        nullable: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Jane Doe
                    email:
                      type: string
                      example: jane@example.com
                    status:
                      type: string
                      example: active
    patch:
      summary: Updates a user
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      parameters: []
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully data updated
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Jane Patched
                      email:
                        type: string
                        example: jane@example.com
                      role:
                        type: string
                        example: user
                      status:
                        type: string
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                      deleted_at:
                        type: string
                        format: date-time
                        nullable: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Jane Doe
                    email:
                      type: string
                      example: jane@example.com
                    status:
                      type: string
                      example: active
    delete:
      summary: Deletes a user
      tags:
      - Users
      security:
      - bearer_auth: []
        x_api_gateway_key: []
      responses:
        '200':
          description: User deleted successfully
security:
- bearer_auth: []
- api_gateway_key: []
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.bdmade.dev
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
    x_api_gateway_key:
      type: apiKey
      name: x-api-gateway-key
      in: header
